### ISSUE TITLE
Error when creating new project

### ISSUE THREAD

**Issue by simonwex** [mozilla/build.webmaker.org#51] opened 2015-02-19 02:09 UTC
```
Connect
500 TypeError: Object #<Object> has no method 'add'
   at /app/server/controllers/schedule.js:29:15
   at module.exports (/app/server/models/form.js:39:3)
   at exports.createPost (/app/server/controllers/schedule.js:26:3)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
   at next (/app/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
   at /app/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)
   at next (/app/node_modules/express/lib/router/index.js:261:10)
```

![image](https://cloud.githubusercontent.com/assets/25260/6260813/192a73bc-b799-11e4-9e2c-02282a3e947f.png)

**Comment by alicoding** [comment] 2015-02-19 18:14
I just hit the same just now.

**Comment by adamlofting** [comment] 2015-03-18 11:48
I filed a dupe for this.
I'll close this version as the other one has steps to reproduce: #62

**Closed as completed by adamlofting** 2015-03-18 11:48 UTC
Labels: bug, critical
